config/routes.rb
Myauth::Application.routes.draw do
  resources :users
  resources :sessions
  resources :lists
  resources :listqueries

  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "done" => "lists#done"
  get "undone" => "lists#undone"

  get "browsers/desktop"
  get "browsers/mobile"
  
  root :to => "pages#new"
  
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  attr_accessor :voper


end

app/models/listquery.rb
class Listquery < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists
  has_one :listquery
  attr_accessible :email, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  before_filter :set_iphone_format
  helper_method :is_iphone_request?

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def is_iphone_request?
      request.user_agent =~ /(Mobile\/.+Safari)/
    end
  
  def set_iphone_format
      if is_iphone_request?
        request.format = :iphone
      end
    end
 
   def set_iphone_format
      if is_iphone_request? or request.format.to_sym == :iphone
        request.format = if cookies["browser"] == "desktop"
                         then :html
                         else :iphone
                         end
      end
    end


end

app/controllers/browsers_controller.rb
class BrowsersController < ActionController::Base
   def desktop
        cookies["browser"] = "desktop"
        redirect_to lists_path
      end

      def mobile
        cookies["browser"] = "mobile"
        redirect_to lists_path
      end

end

app/controllers/listqueries_controller.rb
class ListqueriesController < ApplicationController

  def index
     @listquery = Listquery.where(:user_id => current_user.id)
        respond_to do |format|
      format.html # index.html.erb
        end
  end

  def edit
    @listquery = Listquery.where(:user_id => current_user.id).find(params[:id])
  end

   def show
       @listquery = Listquery.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
     @listquery = Listquery.new
  end

  def create
 @listquery = Listquery.new(params[:listquery])
    respond_to do |format|
      if @listquery.save
        format.html { redirect_to(listqueries_path, :notice => 'Search profile created' ) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def destroy
 @listquery = Listquery.find(params[:id])
    @listquery.destroy
    respond_to do |format|
      format.html { redirect_to(listqueries_url) }
    end
  end

  def update
    @listquery = Listquery.find(params[:id])
    respond_to do |format|
      if @listquery.update_attributes(params[:listquery])
        format.html { redirect_to(@listquery, :notice => 'Search profile updated.') }
      else
      format.html { render :action => "edit" }
      end
  end
  end



end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
        @list = List.where(:user_id => current_user.id).order(:store)
        respond_to do |format|
        format.html # index.html.erb
        format.iphone # index.iphone.erb
        end
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params[:list])
    respond_to do |format|
      if @list.save
        format.html { redirect_to(lists_path, :notice => 'Item added') }
        format.iphone { redirect_to(lists_path, :notice => 'Item added' ) }
      else
        format.html { render :action => "new" }
        format.iphone { redirect_to(lists_path, :notice => 'Item added' ) }
      end
    end
  end

  def show
    @list = List.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.iphone
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    respond_to do |format|
      format.html { redirect_to(lists_path,:notice => 'Item Deleted')}
      format.iphone { redirect_to(lists_path,  :notice => 'Item Deleted') }
    end
  end

   def done
  @list = List.find(params[:id])
  if @list.mdone?
  @list.update_attributes(:mdone => 0)
  else
   @list.update_attributes(:mdone => 1)
  end
     respond_to do |format|
        format.html { redirect_to(lists_path, :notice => 'Done') }
        format.iphone { redirect_to(lists_path, :notice => 'Done') }
     end
    end

  def update
     @list = List.find(params[:id])
    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to(lists_path, :notice => 'Item updated.') }
        format.iphone { redirect_to(lists_path, :notice => 'Item updated.') }
      else
      format.html { render :action => "edit" }
      format.iphone { render :action => "edit" }
      end
    end

  end
 def edit
    @list = List.find(params[:id])
  end
  
 
  def search
     @list = List.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def new
    respond_to do |format|
        format.html # new.html.erb
        format.iphone # new.iphone.erb
        end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
      respond_to do |format|
        format.html # new.html.erb
        format.iphone # new.iphone.erb
        end
    end

    def create
      user = User.authenticate(params[:email], params[:password])
      if user
        session[:user_id] = user.id
        redirect_to lists_path, :notice => current_user.email
      else
        flash.now.alert = "Bad login"
        render "new"
      end
    end

    def destroy
      session[:user_id] = nil
      @cu = 2
      redirect_to root_path, :notice =>  "Logged out"

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
 respond_to do |format|
        format.html # new.html.erb
        format.iphone # new.iphone.erb
        end
  end

  def create
     @user = User.new(params[:user])
    if @user.save
      redirect_to root_path, :notice => "Signed up"
    else
      render "new"
    end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listqueries_helper.rb
module ListqueriesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Shopping list</title>

  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  
</head>
<body>
<h1 id="header"><%= "Shopping List" %></h1>

   <div id="user_nav">
  <% if current_user %>
    Welcome back.... <%= current_user.email %><br />
    <br/>
   <%= link_to "Home", root_path %>
   <%= link_to "See list", lists_path %>
   <%= link_to "Log out", log_out_path %>
  <br/>

  <% else %>
    <%= link_to "Home", root_path %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "Log in", log_in_path %> 
     <br/>
  <% end %>
</div> 
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/layouts/application.iphone.erb
<head>
  <title>Shopping list</title>
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.min.css" />
   <%= javascript_include_tag :defaults %>
   <script src="http://code.jquery.com/jquery-1.5.min.js"></script>
   <script src="http://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.min.js"></script>
  <%= csrf_meta_tag %>
</head>
<body>
  <div data-role= "page" >
  <%= yield%>
  </div>
</body>

app/views/layouts/xxx_application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Shopping list: <%= controller.action_name %></title>
<meta name = "viewport" content = "width = device-width, user-scalable = no" />


  <%= stylesheet_link_tag "iphone","desktop" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  
</head>
<body>
<h1 id="header"><%= "Shopping List" %></h1>

   <div id="user_nav">
  <% if current_user %>
    Welcome back.... <%= current_user.email %><br />
    <br/>
   <%= link_to "Home", root_path %>
   <%= link_to "See list", lists_path %>
   <%= link_to "Log out", log_out_path %>
  <br/>

  <% if false %>
    <% if is_iphone_request? %>
      <%= link_to "Switch To Mobile Safari View",
          {:controller => "browsers", :action => :mobile},
          :class => "big_link"  %>
    <% end %>

  <%= link_to "Switch To Desktop View",
          {:controller => "browsers", :action => :desktop},
          :class => "mobile_link"  %>
<% end %>

  <% else %>
    <%= link_to "Home", root_path %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "Log in", log_in_path %> 
     <br/>
  <% end %>
</div> 


  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/listqueries/_form.html.erb
<%= form_for @listquery do |f| %>
  <p>
    <%= f.label :sfield %>
    <%= f.text_field :sfield %>
  </p>
  <p>
    <%= f.label :soper %>
     <%= f.text_field :soper %>
  </p>
   <p>
    <%= f.label :svalue %>
    <%= f.text_field :svalue %>
  </p>
    <p>
    <%= f.label :sbind %>
    <%= f.text_field :sbind %>
  </p>

      <p>
    <%= f.hidden_field :user_id, :value => current_user.id %>
</p>

  <div class="actions">
    <%= f.submit 'Add Or Update record'%>
  </div>

<% end %>

app/views/listqueries/edit.html.erb
<h1>Update / Review Search Criteria</h1>

<%= render 'form' %>

<%= link_to 'Show', @listquery %> |
<%= link_to 'Back', listquery_path %>

app/views/listqueries/index.html.erb
<h1>Search profile</h1>

<table>
  <tr>
    <th>Field</th>
    <th>Operator</th>
    <th>Field Value</th>
    <th>Binding</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @listquery.each do |listquery| %>
  <tr>
    <td><%= listquery.sfield %></td>
    <td><%=listquery.soper %></td>
    <td><%= listquery.svalue %></td>
    <td><%= listquery.sbind %></td>

    <td><%= link_to 'Edit', edit_listquery_path(listquery) %></td>
    <td><%= link_to 'Delete', listquery, :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add new item', new_listquery_path %>

app/views/listqueries/new.html.erb
<h1>Add new search condition</h1>

<%= render 'form' %>

<%= link_to 'Back', listqueries_path %>

app/views/listqueries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Listquery:</b>
  <%= @listquery.sfield %>
</p>




<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <p>
    <%= f.label "Date" %>
    <%= f.text_field :crdate, :value => Date.today.strftime("%v")  %>
  </p>
  <p>
    <%= f.label :store %>
     <%= f.text_field :store %>
    
  </p>
   <p>
    <%= f.label :item %>
    <%= f.text_field :item %>
  </p>
    <p>
    <%= f.label :qty %>
    <%= f.text_field :qty, :value => 1 %>
  </p>

      <p>
    <%= f.hidden_field :user_id, :value => current_user.id %>
</p>

  <div class="actions">
    <%= f.submit 'Add Item'%>
  </div>

<% end %>

app/views/lists/_form.iphone.erb
<%= form_for @list do |f| %>
  <p>
    <%= f.label "Date" %>
    <%=  f.text_field :crdate, :value => Date.today.strftime("%v") %>
  </p>
  <p>
    <%= f.label :store %>
     <%= f.text_field :store, :size => 20 %>

  </p>
   <p>
    <%= f.label :item %>
    <%= f.text_field :item %>
  </p>
    <p>
    <%= f.label :qty %>
    <%= f.text_field :qty, :value => 1 %>
  </p>

      <p>
    <%= f.hidden_field :user_id, :value => current_user.id %>
</p>

  <div class="actions">
    <%= f.submit 'Save Item'%>
  </div>

<% end %>

app/views/lists/done.html.erb
<p>
  <b>Inside Done:</b>
  <%= @list.item %>
</p>

<p>
  <b>Details:</b>
  <%= @list.qty %>
</p>


<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/edit.iphone.erb
<div data-role="header">
 <h1>Edit item</h1>
    <%= link_to "Back", lists_path, "data-icon" => "plus", "class" => "ui-btn-left" %>
</div>

<div data-role = "content">
<%= render 'form' %>
</div>

app/views/lists/index.html.erb
<table>
  <tr>
    <th>Date</th>
    <th>Store</th>
    <th>Item</th>
    <th>Qty</th>
    <th>Done</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @list.each do |list| %>
  <tr>
    <td><%= list.crdate.strftime("%D") %></td>
    <td><%= list.store %></td>
    <td><%= list.item %></td>
    <td><%= list.qty %></td>
     <td><%= list.mdone %></td>

    <%  if list.mdone? %>
    <td><%= link_to 'UnDone', :controller => "lists", :action => "done", :id => list %></td>
   <%  else %>
   <td><%= link_to '  Done', :controller => "lists", :action => "done", :id => list %></td>
  <%    end %>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Delete', list, :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add new item', new_list_path %>

app/views/lists/index.iphone.erb
<div data-role="header">
<h1>Shopping list</h1>
<%= link_to "Log Out", log_out_path, "data-icon" => "plus", "class" => "ui-btn-left", :notice => @cu %>
<%= link_to 'Add', new_list_path, :notice => 'Add items', "data-icon" => "plus", "class" => "ui-btn-right" %>
</div>

<div data-role="content">
  <ul data-role="listview">
      <% @list.each do |list| %>
        <li>
          <%= link_to list.crdate.to_s+", "+list.store+", "+list.item+", "+list.qty, edit_list_path(list), "data-filter" => true %>
          <%= link_to 'Delete',list, :method => :delete,"data-icon" => 'delete' %>
          <% # .strftime("%e-%b") %>
        </li>
     <% end %>
  </ul>
</div>

<div  data-role="footer">
    (c) zLista : <%= flash[:notice] %>
  </div>

app/views/lists/new.html.erb
<h1>Add new item to list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/new.iphone.erb
<div data-role="header">
<h1>Shopping list</h1>
<%= link_to "Back", lists_path, "arrow-l" => "plus", "class" => "ui-btn-left" %>
</div>

<div data-role="content">
<%= render 'form' %>
</div>

app/views/lists/search.html.erb
<h1>Search</h1>

<%= form_for @list do |f| %>
  
  <p>
    <%= f.label :crdate %>
    <%= f.date_select :crdate %>
  </p>
  <p>
     <%= f.select (:voper, ("<option><</option>,<option>></option>,<option><=</option>,<option>>=</option>,<option>=</option>").html_safe)  %><br />
  </p>
 

  <p class="button"><%= f.submit%></p>
<% end %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>List:</b>
  <%= @list.item %>
</p>

<p>
  <b>Details:</b>
  <%= @list.qty %>
</p>


<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/lists/show.iphone.erb
<p>
  <b>List:</b>
  <%= @list.item %>
</p>

<p>
  <b>Details:</b>
  <%= @list.qty %>
</p>


<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/pages/new.html.erb
<h3>Welcome back to your shopping list. </h3>
<h4>Sign up or log in!</h4>

app/views/pages/new.iphone.erb
 <div data-role="header">
<% if  current_user %>
   <h1>Shopping List</h1>
   <%= link_to "See list", lists_path, "data-icon" => "plus", "class" => "ui-btn-right" %>
   <%= link_to "Log out", log_out_path, "data-icon" => "plus", "class" => "ui-btn-left" %>
  <% else %>
   <h1>Shopping List</h1>
   <%= link_to "Sign up", sign_up_path, "data-icon" => "plus", "class" => "ui-btn-left" %>
    <%= link_to "Log in", log_in_path, "data-icon" => "plus", "class" => "ui-btn-right" %>
  <% end %>

</div>
<div  data-role="footer">
    (c) zLista : <%= flash[:notice] %>
  </div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>

<% end %>

app/views/users/new.iphone.erb
<div data-role="header">
<h1>Sign up</h1>
<%= link_to "Back", root_url, "data-icon" => "arrow-l", "class" => "ui-btn-left" %>
</div>

<div data-role="content">
  
<%= form_for @user do |f| %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit 'Sign up' %></p>

<% end %>
</div>

<div  data-role="footer">
    (c) zLista : <%= flash[:notice] %>
  </div>